### ISSUE TITLE
关于依赖socket.io安装失败的问题

### ISSUE THREAD

**Issue by Jowekk** [CarryHJR/coplayer#2]
您好，十分感谢您的开源！
       我希望能够使用到您的这个开源项目，但是我不太懂npm，在安装依赖的时候遇到了一些困难，安装 socket.io总是各种失败，google了一阵子，感觉像是版本问题，希望您能给与一点思路。

`root@iZ2vc73dy2czl4yhljwhq2Z:~/coplayer/coplayer# npm install --save socket.io --registry=https://registry.npm.taobao.org
npm WARN package.json socket-chat-example@0.0.1 No repository field.
npm http GET https://registry.npm.taobao.org/socket.io
npm http 200 https://registry.npm.taobao.org/socket.io
npm WARN engine socket.io@3.1.0: wanted: {"node":">=10.0.0"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm http GET https://registry.npm.taobao.org/accepts
npm http GET https://registry.npm.taobao.org/base64id
npm http GET https://registry.npm.taobao.org/debug
npm http GET https://registry.npm.taobao.org/engine.io
npm http GET https://registry.npm.taobao.org/socket.io-adapter
npm http GET https://registry.npm.taobao.org/socket.io-parser
npm http 200 https://registry.npm.taobao.org/accepts
npm http 200 https://registry.npm.taobao.org/base64id
npm http 200 https://registry.npm.taobao.org/engine.io
npm http 200 https://registry.npm.taobao.org/socket.io-parser
npm http 200 https://registry.npm.taobao.org/debug
npm http 200 https://registry.npm.taobao.org/socket.io-adapter
npm http GET https://registry.npm.taobao.org/types/cookie
npm http GET https://registry.npm.taobao.org/types/cors
npm http GET https://registry.npm.taobao.org/types/node
npm http 405 https://registry.npm.taobao.org/types/cookie
npm http 405 https://registry.npm.taobao.org/types/node
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-85-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "socket.io" "--registry=https://registry.npm.taobao.org"
npm ERR! cwd /root/coplayer/coplayer
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-85-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "socket.io" "--registry=https://registry.npm.taobao.org"
npm ERR! cwd /root/coplayer/coplayer
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm http 405 https://registry.npm.taobao.org/types/cors
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-85-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "socket.io" "--registry=https://registry.npm.taobao.org"
npm ERR! cwd /root/coplayer/coplayer
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/coplayer/coplayer/npm-debug.log
npm ERR! not ok code 0
`

**Comment by CarryHJR** [comment]
看起来是你个人的环境问题，我谷歌到 https://www.cnblogs.com/edensyd/p/10167348.html ，不知道对你有无帮助
